// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTSz5UdGtWtY8nRSH9F2jJ-aIL7hjY98s',
    appId: '1:411889459724:web:725f7710521deda6958429',
    messagingSenderId: '411889459724',
    projectId: 'park-a-lot-25cdb',
    authDomain: 'park-a-lot-25cdb.firebaseapp.com',
    storageBucket: 'park-a-lot-25cdb.appspot.com',
    measurementId: 'G-7LVZS3JLDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC311EJM4x5h048C-LaG4DjwNZl3qUQS_k',
    appId: '1:411889459724:android:d685df603b2c4254958429',
    messagingSenderId: '411889459724',
    projectId: 'park-a-lot-25cdb',
    storageBucket: 'park-a-lot-25cdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIs7R2T_RUV9fIDC1fdsHZWAFc4CmW_l8',
    appId: '1:411889459724:ios:5a9e2d28f82cd471958429',
    messagingSenderId: '411889459724',
    projectId: 'park-a-lot-25cdb',
    storageBucket: 'park-a-lot-25cdb.appspot.com',
    iosClientId:
        '411889459724-ootsvlp1ltht5pjdepiej5cn19ushogd.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkAlot',
  );
}
